server:
  port: ${SERVICE_PORT:16518}
  servlet:
    encoding:
      charset: UTF-8
      force: true

info:
  component: "@project.name@"        #getting service name
  description: "@project.description@" #getting service description
  version: "@project.version@"        #getting the service version

spring:
  application:
    name: ehub

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ehub-db)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ehub)))
    username: ehub1
    password: eehub1

  jpa:
    hibernate:
      ddl-auto: none

cxf:
  path: /api
  jaxrs:
    client:
      address: http://localhost:16518/api
      classes-scan-packages: sample.rs.service.api
      headers:
        accept: text/plain

logging:
  config: classpath:log4j2-default.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
